apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2-app
  template:
    metadata:
      labels:
        app: container2-app
    spec:
      containers:
        - name: container2
          image: us-west1-docker.pkg.dev/cloud-assignment-2-428721/a3-repo1/a3image2:PLACEHOLDER_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: data-volume
              mountPath: /jainish_PV_dir
      imagePullSecrets:
        - name: gcr-json-key
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: host-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: container2-service
spec:
  selector:
    app: container2-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 5000
